-- BASE
CREATE TABLE IF NOT EXISTS `users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

-- TYPES
CREATE TABLE IF NOT EXISTS `type_entries_categories` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `type_pix_keys` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- FK
CREATE TABLE IF NOT EXISTS `pix` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_KEY_TYPE` INT NOT NULL,
  `ID_USER` INT NOT NULL,
  `KEY` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ID_KEY_TYPE`) REFERENCES `type_pix_keys`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `banks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_USER` INT NOT NULL,
  `ID_PIX` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `AGENCY` VARCHAR(255) NOT NULL,
  `ACCOUNT` VARCHAR(255) NOT NULL,
  `OBSERVATION` VARCHAR(255),
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ID_USER`) REFERENCES `users`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`ID_PIX`) REFERENCES `pix`(`ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `entries` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_BANK` INT NOT NULL,
  `ID_CATEGORY_TYPE` INT NOT NULL,
  `DATE` DATE NOT NULL,
  `VALUE` FLOAT(2) NOT NULL,
  `OBSERVATION` VARCHAR(255),
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ID_BANK`) REFERENCES `banks`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`ID_CATEGORY_TYPE`) REFERENCES `type_entries_categories`(`ID`) ON DELETE CASCADE
);